<!-- components/admin/AddOperatorModal.vue -->
<template>
  <div
    v-if="show"
    class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"
  >
    <div
      class="bg-slate-800 rounded-xl border border-slate-700 w-full max-w-md"
    >
      <div class="p-6">
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-xl font-bold text-white">Add New Operator</h3>
          <button @click="closeModal" class="text-slate-400 hover:text-white">
            <svg
              class="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              ></path>
            </svg>
          </button>
        </div>

        <form @submit.prevent="addOperator" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-slate-300 mb-2">
              Full Name
            </label>
            <input
              v-model="newOperator.name"
              type="text"
              required
              @input="generateAutoEmail"
              class="w-full bg-slate-700 border border-slate-600 text-white px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Enter operator's full name"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-slate-300 mb-2">
              Assign to Stall
            </label>
            <select
              v-model="newOperator.stallId"
              @change="generateAutoEmail"
              class="w-full bg-slate-700 border border-slate-600 text-white px-3 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">No assignment (can assign later)</option>
              <option
                v-for="stall in availableStalls"
                :key="stall.id"
                :value="stall.id"
              >
                {{ stall.name }} - {{ stall.category }}
              </option>
            </select>
          </div>

          <!-- Auto-Generated Email Preview -->
          <div>
            <label class="block text-sm font-medium text-slate-300 mb-2">
              Auto-Generated Email
              <span class="text-green-400 text-xs"
                >(automatically created)</span
              >
            </label>
            <div class="relative">
              <input
                :value="autoGeneratedEmail"
                type="email"
                readonly
                class="w-full bg-slate-600 border border-slate-500 text-slate-300 px-3 py-2 rounded-lg cursor-not-allowed"
                placeholder="Email will be generated automatically..."
              />
              <div class="absolute right-3 top-1/2 transform -translate-y-1/2">
                <svg
                  class="w-5 h-5 text-green-400"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M13 10V3L4 14h7v7l9-11h-7z"
                  ></path>
                </svg>
              </div>
            </div>
            <p class="text-xs text-slate-400 mt-1">
              Based on stall name and merchant domain
            </p>
          </div>

          <!-- Auto-Generated Password Preview -->
          <div>
            <label class="block text-sm font-medium text-slate-300 mb-2">
              Auto-Generated Password
              <span class="text-green-400 text-xs"
                >(secure random password)</span
              >
            </label>
            <div class="relative">
              <input
                :value="autoGeneratedPassword"
                :type="showPassword ? 'text' : 'password'"
                readonly
                class="w-full bg-slate-600 border border-slate-500 text-slate-300 px-3 py-2 pr-20 rounded-lg cursor-not-allowed"
                placeholder="Password will be generated automatically..."
              />
              <div
                class="absolute right-3 top-1/2 transform -translate-y-1/2 flex gap-2"
              >
                <button
                  type="button"
                  @click="generateNewPassword"
                  class="text-blue-400 hover:text-blue-300"
                  title="Generate new password"
                >
                  <svg
                    class="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                    ></path>
                  </svg>
                </button>
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="text-slate-400 hover:text-white"
                >
                  <svg
                    v-if="showPassword"
                    class="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L3 3m6.878 6.878L21 21"
                    ></path>
                  </svg>
                  <svg
                    v-else
                    class="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                    ></path>
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                    ></path>
                  </svg>
                </button>
              </div>
            </div>
            <p class="text-xs text-slate-400 mt-1">
              Operator will be asked to change this password on first login
            </p>
          </div>

          <div class="flex gap-3 pt-4">
            <button
              type="button"
              @click="closeModal"
              class="flex-1 px-4 py-2 text-slate-300 border border-slate-600 rounded-lg hover:bg-slate-700 transition-colors duration-200"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="!autoGeneratedEmail || !autoGeneratedPassword"
              class="flex-1 px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-slate-600 disabled:cursor-not-allowed text-white rounded-lg transition-colors duration-200"
            >
              Create Account
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from "vue"

// Props
const props = defineProps({
  show: {
    type: Boolean,
    default: false,
  },
  availableStalls: {
    type: Array,
    required: true,
  },
  merchantInfo: {
    type: Object,
    required: true,
  },
})

// Emits
const emit = defineEmits(["close", "operator-created"])

// Reactive data
const showPassword = ref(false)
const newOperator = ref({
  name: "",
  stallId: "",
})
const autoGeneratedEmail = ref("")
const autoGeneratedPassword = ref("")

// Methods
const slugify = (text) => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "") // Remove special characters
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/-+/g, "-") // Replace multiple hyphens with single hyphen
    .trim("-") // Remove leading/trailing hyphens
}

const generateSecurePassword = () => {
  const length = 12
  const charset =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
  let password = ""

  // Ensure at least one of each type
  const lower = "abcdefghijklmnopqrstuvwxyz"
  const upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  const numbers = "0123456789"
  const symbols = "!@#$%^&*"

  password += lower[Math.floor(Math.random() * lower.length)]
  password += upper[Math.floor(Math.random() * upper.length)]
  password += numbers[Math.floor(Math.random() * numbers.length)]
  password += symbols[Math.floor(Math.random() * symbols.length)]

  // Fill the rest randomly
  for (let i = password.length; i < length; i++) {
    password += charset[Math.floor(Math.random() * charset.length)]
  }

  // Shuffle the password
  return password
    .split("")
    .sort(() => Math.random() - 0.5)
    .join("")
}

const generateAutoEmail = () => {
  if (!newOperator.value.name && !newOperator.value.stallId) {
    autoGeneratedEmail.value = ""
    return
  }

  let emailPrefix = ""

  if (newOperator.value.stallId) {
    // Use stall name for email prefix
    const stall = props.availableStalls.find(
      (s) => s.id === newOperator.value.stallId
    )
    if (stall) {
      emailPrefix = slugify(stall.name)
    }
  } else if (newOperator.value.name) {
    // Use operator name if no stall assigned
    emailPrefix = slugify(newOperator.value.name)
  }

  // Fallback to operator ID format
  if (!emailPrefix) {
    const nextId = String(Date.now()).slice(-3)
    emailPrefix = `operator-${nextId}`
  }

  autoGeneratedEmail.value = `${emailPrefix}@${props.merchantInfo.domain}.pos`
}

const generateNewPassword = () => {
  autoGeneratedPassword.value = generateSecurePassword()
}

const initializeAutoGeneration = () => {
  generateNewPassword()
  generateAutoEmail()
}

const closeModal = () => {
  // Reset form
  newOperator.value = {
    name: "",
    stallId: "",
  }
  autoGeneratedEmail.value = ""
  autoGeneratedPassword.value = ""
  showPassword.value = false

  emit("close")
}

const addOperator = () => {
  const operatorData = {
    name: newOperator.value.name,
    email: autoGeneratedEmail.value,
    password: autoGeneratedPassword.value,
    stallId: newOperator.value.stallId || null,
  }

  emit("operator-created", operatorData)
  closeModal()
}

// Watch for modal opening to initialize auto-generation
watch(
  () => props.show,
  (newValue) => {
    if (newValue) {
      initializeAutoGeneration()
    }
  }
)
</script>
